### ISSUE TITLE
How to realize the two-dimensional code of art 

### ISSUE THREAD

**Issue by fenglijunnb** [nogoegst/textqr#1]
If this is the complexity of the picture, then we can also achieve this
![image](https://user-images.githubusercontent.com/48191768/77508523-e2166880-6ea5-11ea-98c7-8f3523e7b5e1.png)

**Comment by unkaktus** [comment]
Hi @fenglijunnb!
I didn't quite catch what you suggest. The library does text-only QR codes, not images.

**Comment by fenglijunnb** [comment]
I think this effect needs to be able to make the two-dimensional code not monotonous, namely art QR code, you see you can achieve

**Comment by fenglijunnb** [comment]
What I actually mean is can you generate that kind of artistic qr code, something like that picture
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77626906-fed39e80-6f80-11ea-8092-31da6e8cf3c9.jpg)
